version: '3.8'

services:
  api:
    build: .
    container_name: reconhecimento-facial-api
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
